---
- name: Deploy WordPress on AWS EC2 instance
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Launch EC2 instance
    ec2:
      instance_type: t2.micro
      image: ami-08e637cea2f053dfa
      region: us-east-1
      key_name: 23rlkey
      wait: yes
      instance_tags:
        Name: WordPress
  - name: Add the new EC2 instance to host group
    add_host:
      hostname: "{{ item.public_dns_name }}"
      groupname: wordpress_instance
    with_items: "{{ ec2.instances }}"
  - name: Install Apache, PHP, and MySQL
    become: yes
    become_user: root
    apt:
      name:
        - apache2
        - php
        - libapache2-mod-php
        - mysql-server
        - php-mysql
      state: present
  - name: Start Apache
    become: yes
    become_user: root
    service:
      name: apache2
      state: started
  - name: Download and extract WordPress
    become: yes
    become_user: root
    unarchive:
      src: https://wordpress.org/latest.tar.gz
      dest: /var/www/html/
      remote_src: yes
  - name: Configure WordPress
    become: yes
    become_user: root
    copy:
      src: wp-config.php
      dest: /var/www/html/wordpress/
  - name: Restart Apache
    become: yes
    become_user: root
    service:
      name: apache2
      state: restarted

